Adds initial documentation on OGNL cache configuration
apache/struts-site pull request #183
Opened 2023-01-22 21:09 UTC by JCgH4164838Gh792C124B5

Hello Struts Development Team.

This is an initial attempt to add some documentation on OGNL cache configuration.  Not sure if the templating structure is OK or not.  Please advise if it can be modified and of use for the documentation site.

Regards.

2023-01-23 07:22 UTC, lukaszlenart requested changes
Looks good, just two minor things and I'm good :)

2023-01-23 07:22 UTC, lukaszlenart commented on source/core-developers/ognl-cache-configuration.md
> +As of Struts 2.6, additional configuration properties have been made available to control the
Could you use "6.0.0" term?

2023-01-23 07:22 UTC, lukaszlenart commented on source/core-developers/ognl-cache-configuration.md
> +As of Struts 2.6, developers may choose to implement their own OGNL cache factories,
Same here, please use "6.0.0" to avoid confusing users

2023-02-05 20:18 UTC, JCgH4164838Gh792C124B5 commented
Hi.  The two requested changes have been made.  Please let me know if any other changes are needed.

2023-02-06 09:08 UTC, lukaszlenart approved these changes

2023-02-06 09:09 UTC, lukaszlenart commented
Thanks, LGTM 👍

2023-02-06 09:09 UTC, merged